"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { ComponentType } from "react";
import { useRouter } from "next/navigation";
import {
  Activity, BarChart3, Boxes, ChevronDown, CircleDollarSign, ClipboardList, Database,
  Gauge, LayoutDashboard, LogOut, Menu, PackageSearch, RefreshCw, Search, Settings,
  ShieldCheck, SlidersHorizontal, UserCog, Users, WalletCards, X, Zap
} from "lucide-react";

type Section = "overview"|"analytics"|"orders"|"users"|"wallets"|"catalog"|"payments"|"provider"|"audit"|"settings"|"security"|"system"|"access"|"reconciliation";
const money=(n:unknown)=>"₦"+(Number(n||0)/100).toLocaleString("en-NG",{minimumFractionDigits:2});
const date=(v:unknown)=>v?new Date(String(v)).toLocaleString():"—";

const nav:[Section,string,string][]=[
 ["overview","Overview","Command center"],["analytics","Analytics","Revenue & activity"],["orders","Orders","Fulfillment queue"],
 ["users","Users","Customers & access"],["wallets","Wallets","Balances & adjustments"],["catalog","Catalog","Products & markup"],
 ["payments","Payments","Funding & ledger"],["reconciliation","Reconciliation","Money & settlement"],["provider","Provider","JejeLaye health"],["audit","Audit log","Admin activity"],["settings","Settings","Platform controls"],["security","Security","Access & protection"],["system","System health","Runtime diagnostics"],["access","Admin access","Roles & permissions"]
];
const ICONS:Record<Section,ComponentType<{size?:number}>>={overview:LayoutDashboard,analytics:BarChart3,orders:ClipboardList,users:Users,wallets:WalletCards,catalog:Boxes,payments:CircleDollarSign,provider:Zap,audit:ShieldCheck,settings:Settings,security:ShieldCheck,system:Database,access:UserCog,reconciliation:CircleDollarSign};

export default function Admin(){
 const router=useRouter();
 const [section,setSection]=useState<Section>("overview");
 const [data,setData]=useState<any>({});
 const [loading,setLoading]=useState(true);
 const [message,setMessage]=useState("");
 const [query,setQuery]=useState("");
 const [mobile,setMobile]=useState(false);
 const [drawer,setDrawer]=useState<any>(null);
 const [busy,setBusy]=useState(false);
 const [customer,setCustomer]=useState<any>(null);

 const request=useCallback(async (url:string,init?:RequestInit)=>{
   const r=await fetch(url,{...init,cache:"no-store",credentials:"include"});
   const b=await r.json().catch(()=>({}));
   if(r.status===401||r.status===403){router.replace("/admin-login");throw new Error("Admin access required")}
   if(!r.ok) throw new Error(b.error||"Request failed");
   return b;
 },[router]);
 const load=useCallback(async (s:Section=section)=>{
   setLoading(true);setMessage("");
   try{
    const urls:any={overview:"/api/admin/stats",analytics:"/api/admin/orders",orders:"/api/admin/orders",users:"/api/admin/users",wallets:"/api/admin/wallets",catalog:"/api/admin/catalog",payments:"/api/admin/payments",provider:"/api/admin/health",audit:"/api/admin/audit",settings:"/api/admin/settings",security:"/api/admin/security",system:"/api/admin/health",access:"/api/admin/permissions",reconciliation:"/api/admin/reconciliation"};
    setData(await request(urls[s]));
   }catch(e){setMessage(e instanceof Error?e.message:"Unable to load admin data")}
   finally{setLoading(false)}
 },[request,section]);
 // Data loading is an external-system synchronization; the callback intentionally updates loading/data state.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load(section)},[section,load]);

 async function action(fn:()=>Promise<any>,success:string){
   setBusy(true);setMessage("");
   try{await fn();setMessage(success);await load(section)}catch(e){setMessage(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}
 }
 async function sync(){await action(()=>request("/api/admin/sync",{method:"POST"}),"JejeLaye catalog sync completed.")}
 async function toggleProduct(p:any){await action(()=>request("/api/admin/catalog",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:p.id,active:!p.active})}),"Product status updated.")}
 async function viewCustomer(u:any){setBusy(true);try{setCustomer(await request("/api/admin/users?id="+encodeURIComponent(u.id)))}catch(e){setMessage(e instanceof Error?e.message:"Unable to load customer")}finally{setBusy(false)}}
 async function setRole(u:any,role:string){await action(()=>request("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:u.id,role})}),"User role updated.")}
 async function adjustWallet(){
   if(!drawer?.userId||!drawer.amount||!drawer.reason)return setMessage("Enter amount and reason.");
   await action(()=>request("/api/admin/wallets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:drawer.userId,amountKobo:Math.round(Number(drawer.amount)*100),type:drawer.type,reason:drawer.reason})}),"Wallet adjusted successfully.");
   setDrawer(null);
 }
 async function updateOrder(o:any,status:string){await action(()=>request("/api/admin/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:o.id,status})}),"Order status updated.")}
 async function refundOrder(o:any){const reason=window.prompt("Refund reason");if(!reason)return;await action(()=>request("/api/admin/refunds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:o.id,reason})}),"Order refunded and wallet credited.");}
 async function saveSettings(){
   await action(()=>request("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data.settings||{})}),"Settings saved.");
 }
 const rows=useMemo(()=>Array.isArray(data)?data:[],[data]);
 const filtered=useMemo(()=>rows.filter((r:any)=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const stats=section==="overview"?data:{};
 const funding=data.funding||[], tx=data.transactions||[], webhooks=data.webhooks||[];
 const totalOrders=section==="analytics"?rows.length:stats.orders||0;
 const successful=section==="analytics"?rows.filter((o:any)=>o.status==="completed").length:0;
 const revenue=section==="analytics"?rows.reduce((n:number,o:any)=>n+Number(o.totalKobo||0),0):Number(stats.salesKobo||0);

 return <div className="admin-shell">
  <aside className={mobile?"admin-sidebar open":"admin-sidebar"}>
   <div className="admin-brand"><div className="brand-mark">M</div><div><b>MultiKartX</b><small>ADMIN CONSOLE</small></div><button className="icon-btn mobile-only" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <div className="admin-nav">{nav.map(([id,label,sub])=>{const Icon=ICONS[id];return <button key={id} className={section===id?"admin-nav-item active":"admin-nav-item"} onClick={()=>{setSection(id);setMobile(false)}}><span className="nav-icon"><Icon size={18}/></span><span><b>{label}</b><small>{sub}</small></span></button>})}</div>
   <div className="sidebar-bottom"><div className="secure-pill"><Activity size={15}/> Live system</div><button className="admin-nav-item" onClick={()=>router.push("/")}><LogOut size={18}/><span><b>Exit admin</b><small>Return to app</small></span></button></div>
  </aside>
  {mobile&&<button className="sidebar-overlay" onClick={()=>setMobile(false)} aria-label="Close menu"/>}
  <main className="admin-main">
   <header className="admin-topbar">
    <button className="icon-btn mobile-menu" onClick={()=>setMobile(true)}><Menu size={20}/></button>
    <div className="admin-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search current section…"/></div>
    <div className="top-actions"><span className="status-dot"><i/> Production</span><button className="icon-btn" onClick={()=>load()} title="Refresh"><RefreshCw size={17}/></button><div className="admin-avatar">A</div></div>
   </header>
   <div className="admin-content">
    <div className="admin-heading"><div><span className="eyebrow">ADMINISTRATION</span><h1>{nav.find(n=>n[0]===section)?.[1]}</h1><p>{nav.find(n=>n[0]===section)?.[2]} · live data from Neon</p></div><div className="heading-actions">{(section==="catalog"||section==="provider")&&<button className="btn" onClick={sync} disabled={busy}><RefreshCw size={16}/> Sync JejeLaye</button>}<button className="btn secondary" onClick={()=>load()}><RefreshCw size={16}/> Refresh</button></div></div>
    {message&&<div className="admin-alert">{message}</div>}
    {loading?<div className="loading-card"><Gauge size={22}/> Loading live data…</div>:<>
    {section==="overview"&&<Overview data={stats} on={setSection}/>}
    {section==="analytics"&&<Analytics rows={rows} totalOrders={totalOrders} successful={successful} revenue={revenue}/>}
    {section==="orders"&&<DataTable title="Order operations" rows={filtered} columns={["email","productName","totalKobo","status","providerOrderId","createdAt"]} moneyKeys={["totalKobo"]} onOrder={updateOrder} onRefund={refundOrder}/>}
    {section==="users"&&<DataTable title="Customer accounts" rows={filtered} columns={["email","role","balanceKobo","createdAt"]} moneyKeys={["balanceKobo"]} onRole={setRole}/>}
    {section==="wallets"&&<DataTable title="Wallet control" rows={filtered} columns={["email","balanceKobo","updatedAt"]} moneyKeys={["balanceKobo"]} onWallet={(u:any)=>setDrawer({userId:u.userId,type:"credit",amount:"",reason:""})}/>}
    {section==="catalog"&&<Catalog rows={filtered} onToggle={toggleProduct}/>}
    {section==="payments"&&<Payments funding={funding} transactions={tx} webhooks={webhooks}/>} {section==="reconciliation"&&<Reconciliation data={data}/>}
    {section==="provider"&&<Provider products={rows} onSync={sync}/>}
    {section==="audit"&&<DataTable title="Immutable admin activity" rows={filtered} columns={["adminEmail","action","targetType","targetId","createdAt"]}/>}
    {section==="settings"&&<SettingsPanel data={data.settings||{}} setData={setData} onSave={saveSettings}/>}
    </>}
   </div>
  </main>
  <nav className="mobile-admin-nav" aria-label="Admin quick navigation">
   <button className={section==="overview"?"active":""} onClick={()=>setSection("overview")}><LayoutDashboard size={18}/><span>Home</span></button>
   <button className={section==="orders"?"active":""} onClick={()=>setSection("orders")}><ClipboardList size={18}/><span>Orders</span></button>
   <button className={section==="wallets"?"active":""} onClick={()=>setSection("wallets")}><WalletCards size={18}/><span>Wallet</span></button>
   <button className={section==="catalog"?"active":""} onClick={()=>setSection("catalog")}><Boxes size={18}/><span>Catalog</span></button>
   <button onClick={()=>setMobile(true)}><Menu size={18}/><span>More</span></button>
  </nav>
  {customer&&<div className="modal-backdrop" onClick={()=>setCustomer(null)}><div className="admin-modal customer-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">CUSTOMER PROFILE</span><h2>{customer.profile.email}</h2><small>{customer.profile.role} · joined {date(customer.profile.createdAt)}</small></div><button className="icon-btn" onClick={()=>setCustomer(null)}><X/></button></div><div className="metric-grid compact"><div className="metric-card static"><span className="metric-label">Wallet</span><strong>{money(customer.profile.balanceKobo)}</strong></div><div className="metric-card static"><span className="metric-label">Orders</span><strong>{customer.orders.length}</strong></div></div><div className="customer-list"><h3>Recent orders</h3>{customer.orders.length?customer.orders.slice(0,8).map((o:any)=><div key={o.id}><span><b>{o.productName}</b><small>{date(o.createdAt)} · {o.provider||"—"}</small></span><strong>{money(o.totalKobo)}</strong></div>):<div className="empty">No orders yet.</div>}<h3>Recent wallet activity</h3>{customer.ledger.length?customer.ledger.slice(0,8).map((l:any)=><div key={l.reference}><span><b>{l.type} · {l.description||"Wallet entry"}</b><small>{date(l.createdAt)} · {l.status}</small></span><strong>{money(l.amountKobo)}</strong></div>):<div className="empty">No wallet activity.</div>}</div></div></div>}
  {drawer&&<div className="modal-backdrop"><div className="admin-modal"><div className="modal-head"><div><span className="eyebrow">WALLET CONTROL</span><h2>Adjust balance</h2></div><button className="icon-btn" onClick={()=>setDrawer(null)}><X/></button></div><label>Operation<select value={drawer.type} onChange={e=>setDrawer({...drawer,type:e.target.value})}><option value="credit">Credit</option><option value="debit">Debit</option></select></label><label>Amount (₦)<input inputMode="decimal" value={drawer.amount} onChange={e=>setDrawer({...drawer,amount:e.target.value})}/></label><label>Reason<textarea value={drawer.reason} onChange={e=>setDrawer({...drawer,reason:e.target.value})}/></label><button className="btn wide" disabled={busy} onClick={adjustWallet}>Apply adjustment</button></div></div>}
 </div>
}

function Overview({data,on}:{data:any;on:(s:Section)=>void}){const cards=[["Users",data.users,Users,"users"],["Orders",data.orders,ClipboardList,"orders"],["Active products",data.activeProducts,PackageSearch,"catalog"],["Sales",money(data.salesKobo),CircleDollarSign,"analytics"],["Funding",money(data.fundingKobo),WalletCards,"payments"]];return <><div className="metric-grid">{cards.map(([label,value,Icon,target]:any)=><button className="metric-card" key={label} onClick={()=>on(target)}><span className="metric-icon"><Icon size={20}/></span><span className="metric-label">{label}</span><strong>{value??"—"}</strong><small>View details →</small></button>)}</div><div className="admin-grid two"><div className="panel"><div className="panel-head"><div><h2>Operations</h2><p>Key areas that need attention</p></div></div><div className="ops-list"><button onClick={()=>on("orders")}><ClipboardList/><span><b>Order queue</b><small>Review pending, failed and reported orders</small></span><ChevronDown/></button><button onClick={()=>on("catalog")}><Boxes/><span><b>Provider catalog</b><small>Sync and control customer-facing products</small></span><ChevronDown/></button><button onClick={()=>on("wallets")}><WalletCards/><span><b>Wallet operations</b><small>Credit or debit customer balances with audit trails</small></span><ChevronDown/></button><button onClick={()=>on("provider")}><Database/><span><b>Provider health</b><small>Check JejeLaye connectivity and catalog freshness</small></span><ChevronDown/></button></div></div><div className="panel"><div className="panel-head"><div><h2>Security</h2><p>Administration controls</p></div></div><div className="security-list"><div><ShieldCheck/><span><b>Admin authentication</b><small>Admin-only API guards enabled</small></span><em>Protected</em></div><div><SlidersHorizontal/><span><b>Audit trail</b><small>Administrative mutations are recorded</small></span><em>Enabled</em></div><div><Database/><span><b>Database</b><small>Neon PostgreSQL runtime</small></span><em>Connected</em></div></div></div></div></>}
function Analytics({rows,totalOrders,successful,revenue}:{rows:any[];totalOrders:number;successful:number;revenue:number}){const failed=rows.filter((o:any)=>o.status==="failed").length;const pending=rows.filter((o:any)=>["pending","processing"].includes(o.status)).length;return <><div className="metric-grid compact"><div className="metric-card static"><span className="metric-icon"><ClipboardList/></span><span className="metric-label">Orders loaded</span><strong>{totalOrders}</strong></div><div className="metric-card static"><span className="metric-icon"><Zap/></span><span className="metric-label">Completed</span><strong>{successful}</strong></div><div className="metric-card static"><span className="metric-icon"><Activity/></span><span className="metric-label">Pending</span><strong>{pending}</strong></div><div className="metric-card static"><span className="metric-icon"><CircleDollarSign/></span><span className="metric-label">Gross order value</span><strong>{money(revenue)}</strong></div></div><div className="panel"><div className="panel-head"><div><h2>Order status distribution</h2><p>Calculated from the live order queue</p></div></div><div className="bar-list">{[["Completed",successful],["Pending / processing",pending],["Failed",failed]].map(([l,v]:any)=><div className="bar-row" key={l}><span>{l}</span><div><i style={{width:Math.max(4,Math.min(100,totalOrders?Number(v)/totalOrders*100:4))+"%"}}/></div><b>{v}</b></div>)}</div></div></>}
function DataTable({title,rows,columns,moneyKeys=[],onOrder,onRole,onWallet,onRefund}:{title:string;rows:any[];columns:string[];moneyKeys?:string[];onOrder?:(r:any,s:string)=>void;onRole?:(r:any,s:string)=>void;onWallet?:(r:any)=>void;onRefund?:(r:any)=>void;onView?:(r:any)=>void}){return <div className="panel table-panel"><div className="panel-head"><div><h2>{title}</h2><p>{rows.length} records loaded</p></div></div>{!rows.length?<div className="empty">No records found.</div>:<div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c}>{c.replace(/([A-Z])/g," $1")}</th>)}{(onOrder||onRole||onWallet||onRefund||onView)&&<th>Actions</th>}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><>{columns.map(c=><td key={c}>{moneyKeys.includes(c)?money(r[c]):c==="createdAt"||c==="updatedAt"?date(r[c]):c==="status"?<span className={"status "+String(r[c]).toLowerCase()}>{r[c]}</span>:String(r[c]??"—")}</td>)}</>{onOrder&&<td><select className="mini-select" value={r.status} onChange={e=>onOrder(r,e.target.value)}><option value="pending">pending</option><option value="processing">processing</option><option value="completed">completed</option><option value="failed">failed</option><option value="reported">reported</option><option value="refunded">refunded</option></select></td>}{onRole&&<td><select className="mini-select" value={r.role} onChange={e=>onRole(r,e.target.value)}><option value="customer">customer</option><option value="admin">admin</option></select></td>}{onWallet&&<td><button className="btn tiny" onClick={()=>onWallet(r)}>Adjust</button></td>}{onRefund&&<td><button className="btn tiny secondary" disabled={r.status==="refunded"} onClick={()=>onRefund(r)}>{r.status==="refunded"?"Refunded":"Refund"}</button></td>}{onView&&<td><button className="btn tiny secondary" onClick={()=>onView(r)}>View</button></td>}</tr>)}</tbody></table></div>}</div>}
function Catalog({rows,onToggle}:{rows:any[];onToggle:(p:any)=>void}){return <div className="panel table-panel"><div className="panel-head"><div><h2>JejeLaye catalog</h2><p>Real provider products currently stored in Neon</p></div></div>{!rows.length?<div className="empty">No catalog products. Run a provider sync.</div>:<div className="table-scroll"><table><thead><tr><th>Product</th><th>Service</th><th>Category</th><th>Provider ID</th><th>Price</th><th>Status</th><th/></tr></thead><tbody>{rows.map((p:any)=><tr key={p.id}><td><b>{p.name}</b><small className="table-sub">{p.description||"Provider catalog item"}</small></td><td>{p.serviceType||"—"}</td><td>{p.category||"—"}</td><td><code>{p.providerProductId||"—"}</code></td><td>{money(p.priceKobo)}</td><td><span className={p.active?"status completed":"status failed"}>{p.active?"Active":"Disabled"}</span></td><td><button className="btn tiny secondary" onClick={()=>onToggle(p)}>{p.active?"Disable":"Enable"}</button></td></tr>)}</tbody></table></div>}</div>}
function Payments({funding,transactions,webhooks}:{funding:any[];transactions:any[];webhooks:any[]}){return <div className="admin-grid two"><div className="panel table-panel"><div className="panel-head"><div><h2>Funding</h2><p>Wallet deposits</p></div></div><div className="table-scroll"><table><thead><tr><th>Customer</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{funding.map(p=><tr key={p.id}><td>{p.email}</td><td><code>{p.reference}</code></td><td>{money(p.amountKobo)}</td><td><span className="status">{p.status}</span></td></tr>)}</tbody></table></div></div><div className="panel table-panel"><div className="panel-head"><div><h2>Wallet ledger</h2><p>Credits and debits</p></div></div><div className="table-scroll"><table><thead><tr><th>Customer</th><th>Type</th><th>Amount</th><th>Reference</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td>{t.email}</td><td>{t.type}</td><td>{money(t.amountKobo)}</td><td><code>{t.reference}</code></td></tr>)}</tbody></table></div></div><div className="panel table-panel"><div className="panel-head"><div><h2>Webhook events</h2><p>Payment/provider callbacks</p></div></div><div className="table-scroll"><table><thead><tr><th>Event</th><th>Reference</th><th>Processed</th></tr></thead><tbody>{webhooks.map(w=><tr key={w.id}><td>{w.eventType}</td><td>{w.reference||"—"}</td><td>{date(w.processedAt)}</td></tr>)}</tbody></table></div></div></div>}
function Provider({products,onSync}:{products:any;onSync:()=>void}){const h=products?.health||products||{};const c=h.catalog||{};const state=c.state||"never_synced";const label=state==="healthy"?"Healthy":state==="stale"?"Stale":"Not synced";const tone=state==="healthy"?"completed":state==="stale"?"pending":"failed";return <div className="admin-grid two"><div className="panel provider-hero"><div className="provider-logo">J</div><span className="eyebrow">PRIMARY PROVIDER</span><h2>JejeLaye</h2><p>Live provider connectivity and catalog freshness. Customer products come from the synchronized Neon catalog.</p><div className="provider-stats"><div><b>{c.total??0}</b><small>Catalog records</small></div><div><b>{c.active??0}</b><small>Active products</small></div><div><b>{c.lastSyncCount??0}</b><small>Last sync</small></div></div><button className="btn wide" onClick={onSync}><RefreshCw size={16}/> Sync provider catalog</button></div><div className="panel"><div className="panel-head"><div><h2>Provider checks</h2><p>Operational indicators</p></div></div><div className="security-list"><div><Zap/><span><b>API connection</b><small>Server-side JejeLaye credentials</small></span><em>{h.providerConfigured?"Configured":"Missing token"}</em></div><div><PackageSearch/><span><b>Catalog cache</b><small>{c.lastSyncAt?date(c.lastSyncAt):"No successful sync recorded"}</small></span><em className={"status "+tone}>{label}</em></div><div><Database/><span><b>Catalog records</b><small>{c.active??0} active · {c.total??0} total</small></span><em>{c.total?"Populated":"Empty"}</em></div></div>{c.lastSyncError&&<div className="admin-alert">{c.lastSyncError}</div>}</div></div>}
function SecurityPanel({data}:{data:any}){return <div className="admin-grid two"><div className="panel"><div className="panel-head"><div><h2>Access security</h2><p>Current administrative protection status</p></div></div><div className="security-list"><div><ShieldCheck/><span><b>Admin session</b><small>Server-side authenticated admin session</small></span><em>{data.sessionProtected?"Protected":"Unknown"}</em></div><div><UserCog/><span><b>Role enforcement</b><small>Administrative mutations require admin access</small></span><em>Enabled</em></div><div><ClipboardList/><span><b>Audit logging</b><small>Mutation events are persisted for review</small></span><em>Enabled</em></div></div></div><div className="panel"><div className="panel-head"><div><h2>Security events</h2><p>Recent administrative activity</p></div></div><div className="security-list">{(data.events||[]).slice(0,8).map((e:any)=><div key={e.id}><Activity/><span><b>{e.action}</b><small>{e.adminEmail||"Admin"} · {date(e.createdAt)}</small></span></div>)}</div></div></div>}
function SystemPanel({data}:{data:any}){return <div className="admin-grid two"><div className="panel"><div className="panel-head"><div><h2>System health</h2><p>Live application dependencies</p></div></div><div className="security-list">{Object.entries(data.health||{}).map(([k,v]:any)=><div key={k}><Database/><span><b>{k}</b><small>{typeof v==="object"?JSON.stringify(v):String(v)}</small></span><em>Checked</em></div>)}</div></div><div className="panel"><div className="panel-head"><div><h2>Runtime</h2><p>Operational environment</p></div></div><div className="security-list"><div><Zap/><span><b>Application</b><small>MultiKartX Admin</small></span><em>Online</em></div><div><Database/><span><b>Database</b><small>Neon PostgreSQL</small></span><em>Online</em></div><div><Activity/><span><b>Catalog</b><small>Provider-backed product records</small></span><em>Live</em></div></div></div></div>}
function SettingsPanel({data,setData,onSave}:{data:any;setData:(x:any)=>void;onSave:()=>void}){const update=(k:string,v:string)=>setData((d:any)=>({...d,settings:{...(d.settings||{}),[k]:v}}));return <div className="panel settings-panel"><div className="panel-head"><div><h2>Platform settings</h2><p>Operational values stored securely in the admin settings table.</p></div></div><div className="settings-grid">{[["platformName","Platform name"],["markupPercent","Default markup (%)"],["lowFloatThreshold","Low float threshold (₦)"],["criticalFloatThreshold","Critical float threshold (₦)"],["alertEmail","Alert email"],["alertPhone","Alert phone"],["maintenanceMode","Maintenance mode (true/false)"]].map(([k,l])=><label key={k}>{l}<input value={data[k]??""} onChange={e=>update(k,e.target.value)}/></label>)}</div><button className="btn" onClick={onSave}>Save platform settings</button></div>}

function AccessPanel({data,currentAdminId}:{data:any;currentAdminId?:string}){
 const admins=Array.isArray(data?.admins)?data.admins:[];
 const permissions=Array.isArray(data?.permissions)?data.permissions:[];
 const grants=Array.isArray(data?.grants)?data.grants:[];
 const [adminId,setAdminId]=useState(currentAdminId||admins[0]?.id||"");
 const [busy,setBusy]=useState("");
 const has=(p:string)=>grants.some((g:any)=>g.userId===adminId&&g.permission===p&&g.granted);
 async function toggle(permission:string){setBusy(permission);try{const r=await fetch("/api/admin/permissions",{method:"PATCH",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({userId:adminId,permission,granted:!has(permission)})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Permission update failed");location.reload()}catch(e){alert(e instanceof Error?e.message:"Permission update failed")}finally{setBusy("")}}
 return <div className="panel"><div className="panel-head"><div><h2>Administrator permissions</h2><p>Fine-grained access controls. Every change is audited.</p></div><select className="mini-select" value={adminId} onChange={e=>setAdminId(e.target.value)}>{admins.map((a:any)=><option key={a.id} value={a.id}>{a.email}</option>)}</select></div>{!admins.length?<div className="empty">No administrator accounts found.</div>:<div className="permission-grid">{permissions.map((p:string)=><button key={p} className={has(p)?"permission-card granted":"permission-card"} onClick={()=>toggle(p)} disabled={!!busy}><span>{has(p)?"✓":"○"}</span><div><b>{p}</b><small>{has(p)?"Granted":"Not granted"}</small></div>{busy===p&&<RefreshCw size={14} className="spin" />}</button>)}</div>}</div>}

function Reconciliation({data}:{data:any}){const d=data||{};const r=d.reconciliation||{};return <div className="admin-grid two"><div className="metric-grid compact"><div className="metric-card static"><span className="metric-label">Wallet balance</span><strong>{money(d.wallets?.balanceKobo)}</strong></div><div className="metric-card static"><span className="metric-label">Ledger net</span><strong>{money(d.ledger?.netKobo)}</strong></div><div className="metric-card static"><span className="metric-label">Difference</span><strong>{money(r.walletVsLedgerKobo)}</strong></div><div className="metric-card static"><span className="metric-label">Pending withdrawals</span><strong>{d.withdrawals?.pending??0}</strong></div></div><div className="panel"><div className="panel-head"><div><h2>Settlement integrity</h2><p>Cross-checks live wallet balances against the confirmed ledger.</p></div></div><div className="security-list"><div><ShieldCheck/><span><b>Wallet ↔ ledger</b><small>Expected difference is ₦0.00</small></span><em>{r.balanced?"Balanced":"Review"}</em></div><div><CircleDollarSign/><span><b>Refunds</b><small>{d.refunds?.count??0} completed · {money(d.refunds?.amountKobo)}</small></span><em>Tracked</em></div><div><WalletCards/><span><b>Withdrawals</b><small>{d.withdrawals?.pending??0} pending · {money(d.withdrawals?.pendingAmountKobo)}</small></span><em>Queue</em></div></div></div></div>}
