"use client";
import {useEffect,useState} from "react";
const money=(n:number)=>"₦"+(n/100).toLocaleString("en-NG",{minimumFractionDigits:2});
type Tab="overview"|"users"|"wallets"|"catalog"|"orders"|"payments"|"audit";
export default function Admin(){
 const[t,setT]=useState<Tab>("overview"),[data,setData]=useState<any>({}),[msg,setMsg]=useState("");
 async function load(tab=t){setMsg("");const urls:any={overview:"/api/admin/stats",users:"/api/admin/users",wallets:"/api/admin/wallets",orders:"/api/admin/orders",payments:"/api/admin/payments",audit:"/api/admin/audit"};if(tab==="catalog"){setData({});return}const r=await fetch(urls[tab]);const d=await r.json();if(!r.ok){setMsg(d.error||"Request failed");return}setData(d)}
 useEffect(()=>{load(t)},[t]);
 async function sync(){const r=await fetch("/api/admin/sync",{method:"POST"});const d=await r.json();setMsg(r.ok?("Synced "+d.synced+" services"):(d.error||"Sync failed"))}
 async function role(userId:string,role:string){const r=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId,role})});const d=await r.json();setMsg(r.ok?"Role updated":d.error);load("users")}
 async function adjust(){const email=prompt("Customer email");if(!email)return;const amount=Number(prompt("Amount in naira"));if(!Number.isFinite(amount)||amount<=0)return;const reason=prompt("Reason")||"Admin wallet adjustment";const u=(data as any[]).find(x=>x.email===email);if(!u){setMsg("Load Users and enter an exact customer email.");return}const type=confirm("OK = credit, Cancel = debit")?"credit":"debit";const r=await fetch("/api/admin/wallets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId:u.id,amountKobo:Math.round(amount*100),type,reason})});const d=await r.json();setMsg(r.ok?"Wallet adjusted":d.error);load("wallets")}
 const tabs:[Tab,string][]=[["overview","Overview"],["users","Users"],["wallets","Wallets"],["catalog","Catalog"],["orders","Orders"],["payments","Payments"],["audit","Audit logs"]];
 return <section className="hero"><p className="badge">MultiKartX Admin</p><h1>Control center</h1><p>Users, wallets, JejeLaye products, orders, Paystack activity and audit history.</p>
 <div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"24px 0"}}>{tabs.map(([id,label])=><button key={id} className={t===id?"btn":"btn secondary"} onClick={()=>setT(id)}>{label}</button>)}</div>
 {msg&&<div className="alert success">{msg}</div>}
 {t==="overview"&&<div className="grid">{[["Users",data.users],["Orders",data.orders],["Active products",data.activeProducts],["Sales",money(data.salesKobo||0)],["Funding",money(data.fundingKobo||0)]].map(x=><article className="card" key={x[0]}><b>{x[0]}</b><h2>{x[1]??"—"}</h2></article>)}</div>}
 {t==="users"&&<div className="card"><h2>Users</h2><table><thead><tr><th>Email</th><th>Role</th><th>Wallet</th><th>Action</th></tr></thead><tbody>{(data as any[]).map(u=><tr key={u.id}><td>{u.email}</td><td>{u.role}</td><td>{money(u.balanceKobo)}</td><td><button className="btn secondary" onClick={()=>role(u.id,u.role==="admin"?"customer":"admin")}>{u.role==="admin"?"Demote":"Make admin"}</button></td></tr>)}</tbody></table></div>}
 {t==="wallets"&&<div className="card"><button className="btn" onClick={adjust}>Adjust wallet</button><table><thead><tr><th>Email</th><th>Balance</th><th>Updated</th></tr></thead><tbody>{(data as any[]).map(w=><tr key={w.id}><td>{w.email}</td><td>{money(w.balanceKobo)}</td><td>{new Date(w.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
 {t==="catalog"&&<div className="card"><h2>JejeLaye catalog</h2><p>Pull current provider services into the Neon product catalog.</p><button className="btn" onClick={sync}>Sync JejeLaye services</button></div>}
 {t==="orders"&&<div className="card"><h2>Orders</h2><table><thead><tr><th>Customer</th><th>Product</th><th>Total</th><th>Status</th><th>Created</th></tr></thead><tbody>{(data as any[]).map(o=><tr key={o.id}><td>{o.email}</td><td>{o.productName}</td><td>{money(o.totalKobo)}</td><td>{o.status}</td><td>{new Date(o.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
 {t==="payments"&&<div className="card"><h2>Paystack funding</h2><table><thead><tr><th>Customer</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{(data.funding||[]).map((p:any)=><tr key={p.id}><td>{p.email}</td><td>{p.reference}</td><td>{money(p.amountKobo)}</td><td>{p.status}</td></tr>)}</tbody></table><h2>Webhook events</h2><table><tbody>{(data.webhooks||[]).map((w:any)=><tr key={w.id}><td>{w.eventType}</td><td>{w.reference}</td><td>{new Date(w.processedAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
 {t==="audit"&&<div className="card"><h2>Admin audit log</h2><table><thead><tr><th>Admin</th><th>Action</th><th>Target</th><th>Time</th></tr></thead><tbody>{(data as any[]).map(a=><tr key={a.id}><td>{a.adminEmail}</td><td>{a.action}</td><td>{a.targetType||""} {a.targetId||""}</td><td>{new Date(a.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
 </section>
}