import axios, { AxiosInstance, AxiosRequestConfig } from 'axios';
import axiosRetry from 'axios-retry';
import CircuitBreaker from 'opossum';
import { randomUUID } from 'node:crypto';

export interface JejeLayeConfig { baseUrl?:string; token:string; onLog?:(entry:Record<string,unknown>)=>Promise<void>|void; }
export interface ProviderResponse<T=unknown>{ data:T; status:number; reference?:string; }

export class JejeLayeError extends Error { constructor(public status:number, message:string, public details?:unknown){super(message);this.name='JejeLayeError';} }

export class JejeLayeClient {
  private readonly axios:AxiosInstance;
  private readonly breaker:CircuitBreaker;
  private readonly config:JejeLayeConfig;
  constructor(config:JejeLayeConfig){
    this.config=config;
    this.axios=axios.create({baseURL:(config.baseUrl||'https://jejelaegyct.com.ng/api/v1').replace(/\/$/,''),timeout:30000,headers:{'Content-Type':'application/json','Accept':'application/json'}});
    axiosRetry(this.axios,{retries:3,retryDelay:(count)=>1000*Math.pow(2,count-1),retryCondition:(error)=>axiosRetry.isNetworkOrIdempotentRequestError(error)||error.response?.status===429||(error.response?.status??0)>=500});
    this.axios.interceptors.request.use((req)=>{req.headers.Authorization=`Bearer ${this.config.token}`;req.headers['X-Idempotency-Key']=String((req as AxiosRequestConfig & {idempotencyKey?:string}).idempotencyKey||randomUUID());return req;});
    this.axios.interceptors.response.use((res)=>res,(err)=>Promise.reject(new JejeLayeError(err.response?.status??0,err.response?.data?.message||err.message,err.response?.data)));
    this.breaker=new CircuitBreaker((method:string,url:string,data?:unknown,headers?:Record<string,string>)=>this.axios.request({method,url,data,headers}),{errorThresholdPercentage:50,resetTimeout:60000,volumeThreshold:5,timeout:35000});
  }
  private async request<T>(method:string,url:string,data?:unknown, idempotencyKey?:string):Promise<ProviderResponse<T>>{const started=Date.now();try{const response=await this.breaker.fire(method,url,data,idempotencyKey?{'X-Idempotency-Key':idempotencyKey}:undefined) as {data:T;status:number};await this.config.onLog?.({method,url,statusCode:response.status,durationMs:Date.now()-started,responseBody:response.data});return response;}catch(error){await this.config.onLog?.({method,url,statusCode:error instanceof JejeLayeError?error.status:0,durationMs:Date.now()-started,error:error instanceof Error?error.message:String(error)});throw error;}}
  get<T>(url:string,params?:Record<string,unknown>){return this.request<T>('GET',url,params);}
  post<T>(url:string,data?:unknown,key?:string){return this.request<T>('POST',url,data,key);}
  patch<T>(url:string,data?:unknown){return this.request<T>('PATCH',url,data);}
  register(dto:unknown){return this.post('/auth/register',dto)} login(dto:unknown){return this.post('/auth/login',dto)} logout(){return this.post('/auth/logout')} me(){return this.get('/auth/me')} forgotPassword(email:string){return this.post('/auth/forgot-password',{email})} resetPassword(dto:unknown){return this.post('/auth/reset-password',dto)} verifyEmail(dto:unknown){return this.post('/auth/verify-email',dto)} resendVerification(email:string){return this.post('/auth/resend-verification',{email})}
  profile(){return this.get('/profile')} updateName(name:string){return this.patch('/profile',{name})} changePassword(dto:unknown){return this.post('/profile/password',dto)} wallet(){return this.get('/wallet')} fundWallet(amount:number){return this.post('/wallet/fund',{amount})} virtualAccount(){return this.post('/wallet/virtual-account')} transferReferral(amount:number){return this.post('/wallet/referral/transfer',{amount})} notifications(){return this.get('/notifications')} markNotifications(ids:string[]){return this.post('/notifications/mark-read',{ids})}
  listTransactions(params?:Record<string,unknown>){return this.get('/transactions',params)} getTransaction(ref:string){return this.get(`/transactions/${encodeURIComponent(ref)}`)} listServices(type?:string){return this.get('/services',type?{type}:undefined)} categories(){return this.get('/categories')} verifyService(id:string,dto:unknown){return this.post(`/services/${encodeURIComponent(id)}/verify`,dto)} purchase(id:string,dto:unknown,key?:string){return this.post(`/services/${encodeURIComponent(id)}/purchase`,dto,key)}
  giftCardCatalog(){return this.get('/gift-cards/catalog')} giftCardRates(slug:string){return this.get('/gift-cards/rates',{slug})} giftCardQuote(dto:unknown){return this.post('/gift-cards/quote',dto)} giftCardTrades(){return this.get('/gift-cards/trades')} giftCardTrade(ref:string){return this.get(`/gift-cards/trades/${encodeURIComponent(ref)}`)} giftCardWallet(){return this.get('/gift-cards/wallet')} giftCardWithdraw(dto:unknown){return this.post('/gift-cards/withdrawals',dto)} giftCardWithdrawals(){return this.get('/gift-cards/withdrawals')} giftCardTransfer(amount:number){return this.post('/gift-cards/wallet/transfer',{amount})} banks(){return this.get('/gift-cards/banks')} resolveBank(dto:unknown){return this.post('/gift-cards/banks/resolve',dto)}
  vnCategories(){return this.get('/virtual-numbers/categories')} vnCatalog(params?:Record<string,unknown>){return this.get('/virtual-numbers/catalog',params)} vnPurchase(dto:unknown,key?:string){return this.post('/virtual-numbers/purchase',dto,key)} vnSessions(){return this.get('/virtual-numbers/sessions')} vnCancel(ref:string,reason:string){return this.post(`/virtual-numbers/sessions/${encodeURIComponent(ref)}/cancel`,{reason})} vnRequestAnother(ref:string){return this.post(`/virtual-numbers/sessions/${encodeURIComponent(ref)}/request-another-sms`)}
  emailCatalog(){return this.get('/email-verification/catalog')} emailPurchase(dto:unknown,key?:string){return this.post('/email-verification/purchase',dto,key)} emailFetchCode(id:string){return this.post(`/email-verification/sessions/${encodeURIComponent(id)}/fetch-code`)} emailCancel(id:string){return this.post(`/email-verification/sessions/${encodeURIComponent(id)}/cancel`)}
  esimCatalog(){return this.get('/esim/catalog')} esimPurchase(dto:unknown,key?:string){return this.post('/esim/purchase',dto,key)} esimSessions(){return this.get('/esim/sessions')} esimSession(ref:string){return this.get(`/esim/sessions/${encodeURIComponent(ref)}`)} esimNickname(ref:string,nickname:string){return this.patch(`/esim/sessions/${encodeURIComponent(ref)}/nickname`,{nickname})} esimTopup(ref:string,package_code:string){return this.post(`/esim/sessions/${encodeURIComponent(ref)}/topup`,{package_code})} esimEmail(ref:string,email:string){return this.post(`/esim/sessions/${encodeURIComponent(ref)}/email`,{email})} esimManage(ref:string,action:string){return this.post(`/esim/sessions/${encodeURIComponent(ref)}/manage`,{action})}
  marketplace(){return this.get('/marketplace')} marketplaceBuy(id:string,key?:string){return this.post('/marketplace/purchase',{id},key)} tutorials(){return this.get('/tutorials')} createTicket(dto:unknown){return this.post('/support-tickets',dto)} listTickets(){return this.get('/support-tickets')} replyTicket(id:string,message:string){return this.post(`/support-tickets/${encodeURIComponent(id)}/reply`,{message})}
}
